// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: buckets.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const bucketUsedBytes = `-- name: BucketUsedBytes :one
SELECT COALESCE(SUM(size), 0)::BIGINT AS used
FROM objects
WHERE bucket_id = $1 AND is_latest AND deleted_at IS NULL
`

func (q *Queries) BucketUsedBytes(ctx context.Context, bucketID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, bucketUsedBytes, bucketID)
	var used int64
	err := row.Scan(&used)
	return used, err
}

const createBucket = `-- name: CreateBucket :one
INSERT INTO buckets (name, owner_id, versioning_enabled, quota_bytes)
VALUES ($1, $2, $3, $4)
RETURNING id, name, owner_id, versioning_enabled, quota_bytes, created_at
`

type CreateBucketParams struct {
	Name              string
	OwnerID           string
	VersioningEnabled bool
	QuotaBytes        int64
}

func (q *Queries) CreateBucket(ctx context.Context, arg CreateBucketParams) (Bucket, error) {
	row := q.db.QueryRow(ctx, createBucket,
		arg.Name,
		arg.OwnerID,
		arg.VersioningEnabled,
		arg.QuotaBytes,
	)
	var i Bucket
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.VersioningEnabled,
		&i.QuotaBytes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBucket = `-- name: DeleteBucket :execrows
DELETE FROM buckets WHERE name = $1
`

func (q *Queries) DeleteBucket(ctx context.Context, name string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBucket, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBucketByName = `-- name: GetBucketByName :one
SELECT id, name, owner_id, versioning_enabled, quota_bytes, created_at FROM buckets WHERE name = $1
`

func (q *Queries) GetBucketByName(ctx context.Context, name string) (Bucket, error) {
	row := q.db.QueryRow(ctx, getBucketByName, name)
	var i Bucket
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.VersioningEnabled,
		&i.QuotaBytes,
		&i.CreatedAt,
	)
	return i, err
}

const listBuckets = `-- name: ListBuckets :many
SELECT id, name, owner_id, versioning_enabled, quota_bytes, created_at FROM buckets ORDER BY name
`

func (q *Queries) ListBuckets(ctx context.Context) ([]Bucket, error) {
	rows, err := q.db.Query(ctx, listBuckets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bucket{}
	for rows.Next() {
		var i Bucket
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.VersioningEnabled,
			&i.QuotaBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
