// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chunks.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const decrementChunkRefcounts = `-- name: DecrementChunkRefcounts :exec
UPDATE chunks
SET refcount = GREATEST(refcount - 1, 0)
WHERE id IN (SELECT chunk_id FROM object_chunks WHERE object_id = $1)
`

// Decrements every chunk referenced by an object version. Clamped at zero so a
// double delete cannot drive the count negative and trip the CHECK constraint.
func (q *Queries) DecrementChunkRefcounts(ctx context.Context, objectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, decrementChunkRefcounts, objectID)
	return err
}

const deleteChunk = `-- name: DeleteChunk :execrows
DELETE FROM chunks WHERE id = $1 AND refcount = 0
`

func (q *Queries) DeleteChunk(ctx context.Context, id []byte) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChunk, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChunk = `-- name: GetChunk :one
SELECT id, size, refcount, ec_scheme, created_at FROM chunks WHERE id = $1
`

func (q *Queries) GetChunk(ctx context.Context, id []byte) (Chunk, error) {
	row := q.db.QueryRow(ctx, getChunk, id)
	var i Chunk
	err := row.Scan(
		&i.ID,
		&i.Size,
		&i.Refcount,
		&i.EcScheme,
		&i.CreatedAt,
	)
	return i, err
}

const getObjectChunkPlacements = `-- name: GetObjectChunkPlacements :many
SELECT
    oc.seq,
    oc.chunk_id,
    oc.byte_offset,
    oc.size,
    COALESCE(
        ARRAY_AGG(n.addr ORDER BY n.addr) FILTER (WHERE n.addr IS NOT NULL),
        ARRAY[]::TEXT[]
    )::TEXT[] AS node_addrs
FROM object_chunks oc
LEFT JOIN chunk_placements p ON p.chunk_id = oc.chunk_id AND p.state = 'ok'
LEFT JOIN nodes n ON n.id = p.node_id
WHERE oc.object_id = $1
GROUP BY oc.seq, oc.chunk_id, oc.byte_offset, oc.size
ORDER BY oc.seq
`

type GetObjectChunkPlacementsRow struct {
	Seq        int32
	ChunkID    []byte
	ByteOffset int64
	Size       int64
	NodeAddrs  []string
}

// One query returns an object's whole chunk list with every live location,
// so reading an object costs a single round trip to the coordinator rather
// than one per chunk.
func (q *Queries) GetObjectChunkPlacements(ctx context.Context, objectID uuid.UUID) ([]GetObjectChunkPlacementsRow, error) {
	rows, err := q.db.Query(ctx, getObjectChunkPlacements, objectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetObjectChunkPlacementsRow{}
	for rows.Next() {
		var i GetObjectChunkPlacementsRow
		if err := rows.Scan(
			&i.Seq,
			&i.ChunkID,
			&i.ByteOffset,
			&i.Size,
			&i.NodeAddrs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlacements = `-- name: GetPlacements :many
SELECT p.chunk_id, p.node_id, p.shard_index, n.addr
FROM chunk_placements p
JOIN nodes n ON n.id = p.node_id
WHERE p.chunk_id = $1 AND p.state = 'ok'
ORDER BY p.shard_index
`

type GetPlacementsRow struct {
	ChunkID    []byte
	NodeID     string
	ShardIndex int32
	Addr       string
}

func (q *Queries) GetPlacements(ctx context.Context, chunkID []byte) ([]GetPlacementsRow, error) {
	rows, err := q.db.Query(ctx, getPlacements, chunkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlacementsRow{}
	for rows.Next() {
		var i GetPlacementsRow
		if err := rows.Scan(
			&i.ChunkID,
			&i.NodeID,
			&i.ShardIndex,
			&i.Addr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementChunkRefcount = `-- name: IncrementChunkRefcount :exec
UPDATE chunks SET refcount = refcount + 1 WHERE id = $1
`

func (q *Queries) IncrementChunkRefcount(ctx context.Context, id []byte) error {
	_, err := q.db.Exec(ctx, incrementChunkRefcount, id)
	return err
}

const listUnreferencedChunks = `-- name: ListUnreferencedChunks :many
SELECT id, size, refcount, ec_scheme, created_at FROM chunks
WHERE refcount = 0 AND created_at < $1
ORDER BY created_at
LIMIT $2
`

type ListUnreferencedChunksParams struct {
	CreatedAt time.Time
	Limit     int32
}

// GC candidates: no references left, and old enough that an upload in flight
// cannot still be about to reference them.
func (q *Queries) ListUnreferencedChunks(ctx context.Context, arg ListUnreferencedChunksParams) ([]Chunk, error) {
	rows, err := q.db.Query(ctx, listUnreferencedChunks, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chunk{}
	for rows.Next() {
		var i Chunk
		if err := rows.Scan(
			&i.ID,
			&i.Size,
			&i.Refcount,
			&i.EcScheme,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPlacementBad = `-- name: MarkPlacementBad :exec
UPDATE chunk_placements
SET state = $3
WHERE chunk_id = $1 AND node_id = $2
`

type MarkPlacementBadParams struct {
	ChunkID []byte
	NodeID  string
	State   string
}

func (q *Queries) MarkPlacementBad(ctx context.Context, arg MarkPlacementBadParams) error {
	_, err := q.db.Exec(ctx, markPlacementBad, arg.ChunkID, arg.NodeID, arg.State)
	return err
}

const upsertChunk = `-- name: UpsertChunk :one
INSERT INTO chunks (id, size)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE SET size = chunks.size
RETURNING id, size, refcount, ec_scheme, created_at, (xmax = 0) AS inserted
`

type UpsertChunkParams struct {
	ID   []byte
	Size int64
}

type UpsertChunkRow struct {
	ID        []byte
	Size      int64
	Refcount  int64
	EcScheme  string
	CreatedAt time.Time
	Inserted  bool
}

// Returns xmax = 0 when the row was inserted rather than updated, which is how
// we tell a genuinely new chunk from a deduplication hit in a single round trip.
func (q *Queries) UpsertChunk(ctx context.Context, arg UpsertChunkParams) (UpsertChunkRow, error) {
	row := q.db.QueryRow(ctx, upsertChunk, arg.ID, arg.Size)
	var i UpsertChunkRow
	err := row.Scan(
		&i.ID,
		&i.Size,
		&i.Refcount,
		&i.EcScheme,
		&i.CreatedAt,
		&i.Inserted,
	)
	return i, err
}

const upsertPlacement = `-- name: UpsertPlacement :exec
INSERT INTO chunk_placements (chunk_id, node_id, shard_index, state, last_verified_at)
VALUES ($1, $2, $3, 'ok', now())
ON CONFLICT (chunk_id, node_id, shard_index)
DO UPDATE SET state = 'ok', last_verified_at = now()
`

type UpsertPlacementParams struct {
	ChunkID    []byte
	NodeID     string
	ShardIndex int32
}

func (q *Queries) UpsertPlacement(ctx context.Context, arg UpsertPlacementParams) error {
	_, err := q.db.Exec(ctx, upsertPlacement, arg.ChunkID, arg.NodeID, arg.ShardIndex)
	return err
}
