// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"

	"github.com/google/uuid"
)

type Bucket struct {
	ID                uuid.UUID
	Name              string
	OwnerID           string
	VersioningEnabled bool
	QuotaBytes        int64
	CreatedAt         time.Time
}

type Chunk struct {
	ID        []byte
	Size      int64
	Refcount  int64
	EcScheme  string
	CreatedAt time.Time
}

type ChunkPlacement struct {
	ChunkID        []byte
	NodeID         string
	ShardIndex     int32
	State          string
	LastVerifiedAt *time.Time
}

type Node struct {
	ID              string
	Addr            string
	Zone            string
	CapacityBytes   int64
	UsedBytes       int64
	State           string
	LastHeartbeatAt *time.Time
	CreatedAt       time.Time
}

type Object struct {
	ID           uuid.UUID
	BucketID     uuid.UUID
	Key          string
	VersionID    uuid.UUID
	Size         int64
	ContentType  string
	Etag         string
	StorageClass string
	Metadata     []byte
	IsLatest     bool
	DeletedAt    *time.Time
	CreatedAt    time.Time
}

type ObjectChunk struct {
	ObjectID   uuid.UUID
	Seq        int32
	ChunkID    []byte
	ByteOffset int64
	Size       int64
}
