// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package dbgen

import (
	"context"
)

const getNode = `-- name: GetNode :one
SELECT id, addr, zone, capacity_bytes, used_bytes, state, last_heartbeat_at, created_at FROM nodes WHERE id = $1
`

func (q *Queries) GetNode(ctx context.Context, id string) (Node, error) {
	row := q.db.QueryRow(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Addr,
		&i.Zone,
		&i.CapacityBytes,
		&i.UsedBytes,
		&i.State,
		&i.LastHeartbeatAt,
		&i.CreatedAt,
	)
	return i, err
}

const listLiveNodes = `-- name: ListLiveNodes :many
SELECT id, addr, zone, capacity_bytes, used_bytes, state, last_heartbeat_at, created_at FROM nodes WHERE state = 'live' ORDER BY id
`

func (q *Queries) ListLiveNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.Query(ctx, listLiveNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Addr,
			&i.Zone,
			&i.CapacityBytes,
			&i.UsedBytes,
			&i.State,
			&i.LastHeartbeatAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodes = `-- name: ListNodes :many
SELECT id, addr, zone, capacity_bytes, used_bytes, state, last_heartbeat_at, created_at FROM nodes ORDER BY id
`

func (q *Queries) ListNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Addr,
			&i.Zone,
			&i.CapacityBytes,
			&i.UsedBytes,
			&i.State,
			&i.LastHeartbeatAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNodeState = `-- name: SetNodeState :exec
UPDATE nodes SET state = $2 WHERE id = $1
`

type SetNodeStateParams struct {
	ID    string
	State string
}

func (q *Queries) SetNodeState(ctx context.Context, arg SetNodeStateParams) error {
	_, err := q.db.Exec(ctx, setNodeState, arg.ID, arg.State)
	return err
}

const updateNodeUsage = `-- name: UpdateNodeUsage :exec
UPDATE nodes
SET used_bytes = $2, last_heartbeat_at = now()
WHERE id = $1
`

type UpdateNodeUsageParams struct {
	ID        string
	UsedBytes int64
}

func (q *Queries) UpdateNodeUsage(ctx context.Context, arg UpdateNodeUsageParams) error {
	_, err := q.db.Exec(ctx, updateNodeUsage, arg.ID, arg.UsedBytes)
	return err
}

const upsertNode = `-- name: UpsertNode :one
INSERT INTO nodes (id, addr, zone, capacity_bytes, state, last_heartbeat_at)
VALUES ($1, $2, $3, $4, 'live', now())
ON CONFLICT (id) DO UPDATE
SET addr = EXCLUDED.addr,
    zone = EXCLUDED.zone,
    capacity_bytes = EXCLUDED.capacity_bytes,
    state = 'live',
    last_heartbeat_at = now()
RETURNING id, addr, zone, capacity_bytes, used_bytes, state, last_heartbeat_at, created_at
`

type UpsertNodeParams struct {
	ID            string
	Addr          string
	Zone          string
	CapacityBytes int64
}

func (q *Queries) UpsertNode(ctx context.Context, arg UpsertNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, upsertNode,
		arg.ID,
		arg.Addr,
		arg.Zone,
		arg.CapacityBytes,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Addr,
		&i.Zone,
		&i.CapacityBytes,
		&i.UsedBytes,
		&i.State,
		&i.LastHeartbeatAt,
		&i.CreatedAt,
	)
	return i, err
}
