// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: objects.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const clearLatestVersion = `-- name: ClearLatestVersion :exec
UPDATE objects
SET is_latest = false
WHERE bucket_id = $1 AND key = $2 AND is_latest
`

type ClearLatestVersionParams struct {
	BucketID uuid.UUID
	Key      string
}

// Demotes the current version of a key. Run inside CommitObject's transaction
// immediately before inserting the new one, so the unique partial index on
// (bucket_id, key) WHERE is_latest is never violated and no reader ever sees
// zero or two current versions.
func (q *Queries) ClearLatestVersion(ctx context.Context, arg ClearLatestVersionParams) error {
	_, err := q.db.Exec(ctx, clearLatestVersion, arg.BucketID, arg.Key)
	return err
}

const getLatestObject = `-- name: GetLatestObject :one
SELECT id, bucket_id, key, version_id, size, content_type, etag, storage_class, metadata, is_latest, deleted_at, created_at FROM objects
WHERE bucket_id = $1 AND key = $2 AND is_latest AND deleted_at IS NULL
`

type GetLatestObjectParams struct {
	BucketID uuid.UUID
	Key      string
}

func (q *Queries) GetLatestObject(ctx context.Context, arg GetLatestObjectParams) (Object, error) {
	row := q.db.QueryRow(ctx, getLatestObject, arg.BucketID, arg.Key)
	var i Object
	err := row.Scan(
		&i.ID,
		&i.BucketID,
		&i.Key,
		&i.VersionID,
		&i.Size,
		&i.ContentType,
		&i.Etag,
		&i.StorageClass,
		&i.Metadata,
		&i.IsLatest,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getObjectVersion = `-- name: GetObjectVersion :one
SELECT id, bucket_id, key, version_id, size, content_type, etag, storage_class, metadata, is_latest, deleted_at, created_at FROM objects
WHERE bucket_id = $1 AND key = $2 AND version_id = $3 AND deleted_at IS NULL
`

type GetObjectVersionParams struct {
	BucketID  uuid.UUID
	Key       string
	VersionID uuid.UUID
}

func (q *Queries) GetObjectVersion(ctx context.Context, arg GetObjectVersionParams) (Object, error) {
	row := q.db.QueryRow(ctx, getObjectVersion, arg.BucketID, arg.Key, arg.VersionID)
	var i Object
	err := row.Scan(
		&i.ID,
		&i.BucketID,
		&i.Key,
		&i.VersionID,
		&i.Size,
		&i.ContentType,
		&i.Etag,
		&i.StorageClass,
		&i.Metadata,
		&i.IsLatest,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertObject = `-- name: InsertObject :one
INSERT INTO objects (
    bucket_id, key, size, content_type, etag, storage_class, metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, bucket_id, key, version_id, size, content_type, etag, storage_class, metadata, is_latest, deleted_at, created_at
`

type InsertObjectParams struct {
	BucketID     uuid.UUID
	Key          string
	Size         int64
	ContentType  string
	Etag         string
	StorageClass string
	Metadata     []byte
}

func (q *Queries) InsertObject(ctx context.Context, arg InsertObjectParams) (Object, error) {
	row := q.db.QueryRow(ctx, insertObject,
		arg.BucketID,
		arg.Key,
		arg.Size,
		arg.ContentType,
		arg.Etag,
		arg.StorageClass,
		arg.Metadata,
	)
	var i Object
	err := row.Scan(
		&i.ID,
		&i.BucketID,
		&i.Key,
		&i.VersionID,
		&i.Size,
		&i.ContentType,
		&i.Etag,
		&i.StorageClass,
		&i.Metadata,
		&i.IsLatest,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertObjectChunk = `-- name: InsertObjectChunk :exec
INSERT INTO object_chunks (object_id, seq, chunk_id, byte_offset, size)
VALUES ($1, $2, $3, $4, $5)
`

type InsertObjectChunkParams struct {
	ObjectID   uuid.UUID
	Seq        int32
	ChunkID    []byte
	ByteOffset int64
	Size       int64
}

func (q *Queries) InsertObjectChunk(ctx context.Context, arg InsertObjectChunkParams) error {
	_, err := q.db.Exec(ctx, insertObjectChunk,
		arg.ObjectID,
		arg.Seq,
		arg.ChunkID,
		arg.ByteOffset,
		arg.Size,
	)
	return err
}

const listDeletableObjects = `-- name: ListDeletableObjects :many
SELECT id, bucket_id, key, version_id, size, content_type, etag, storage_class, metadata, is_latest, deleted_at, created_at FROM objects
WHERE deleted_at IS NOT NULL AND deleted_at < $1
ORDER BY deleted_at
LIMIT $2
`

type ListDeletableObjectsParams struct {
	DeletedAt *time.Time
	Limit     int32
}

// Tombstoned versions whose chunks are ready to be dereferenced.
func (q *Queries) ListDeletableObjects(ctx context.Context, arg ListDeletableObjectsParams) ([]Object, error) {
	rows, err := q.db.Query(ctx, listDeletableObjects, arg.DeletedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Object{}
	for rows.Next() {
		var i Object
		if err := rows.Scan(
			&i.ID,
			&i.BucketID,
			&i.Key,
			&i.VersionID,
			&i.Size,
			&i.ContentType,
			&i.Etag,
			&i.StorageClass,
			&i.Metadata,
			&i.IsLatest,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObjectVersions = `-- name: ListObjectVersions :many
SELECT id, bucket_id, key, version_id, size, content_type, etag, storage_class, metadata, is_latest, deleted_at, created_at FROM objects
WHERE bucket_id = $1 AND key = $2
ORDER BY created_at DESC
`

type ListObjectVersionsParams struct {
	BucketID uuid.UUID
	Key      string
}

func (q *Queries) ListObjectVersions(ctx context.Context, arg ListObjectVersionsParams) ([]Object, error) {
	rows, err := q.db.Query(ctx, listObjectVersions, arg.BucketID, arg.Key)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Object{}
	for rows.Next() {
		var i Object
		if err := rows.Scan(
			&i.ID,
			&i.BucketID,
			&i.Key,
			&i.VersionID,
			&i.Size,
			&i.ContentType,
			&i.Etag,
			&i.StorageClass,
			&i.Metadata,
			&i.IsLatest,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObjects = `-- name: ListObjects :many
SELECT id, bucket_id, key, version_id, size, content_type, etag, storage_class, metadata, is_latest, deleted_at, created_at FROM objects
WHERE bucket_id = $1
  AND is_latest
  AND deleted_at IS NULL
  AND key LIKE $2 || '%'
  AND key > $3
ORDER BY key
LIMIT $4
`

type ListObjectsParams struct {
	BucketID uuid.UUID
	Column2  *string
	Key      string
	Limit    int32
}

// Keyset pagination on (key): stable under concurrent writes, unlike OFFSET,
// and the continuation token is just the last key returned.
func (q *Queries) ListObjects(ctx context.Context, arg ListObjectsParams) ([]Object, error) {
	rows, err := q.db.Query(ctx, listObjects,
		arg.BucketID,
		arg.Column2,
		arg.Key,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Object{}
	for rows.Next() {
		var i Object
		if err := rows.Scan(
			&i.ID,
			&i.BucketID,
			&i.Key,
			&i.VersionID,
			&i.Size,
			&i.ContentType,
			&i.Etag,
			&i.StorageClass,
			&i.Metadata,
			&i.IsLatest,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeObject = `-- name: PurgeObject :exec
DELETE FROM objects WHERE id = $1
`

func (q *Queries) PurgeObject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, purgeObject, id)
	return err
}

const softDeleteObject = `-- name: SoftDeleteObject :execrows
UPDATE objects
SET deleted_at = now(), is_latest = false
WHERE bucket_id = $1 AND key = $2 AND is_latest AND deleted_at IS NULL
`

type SoftDeleteObjectParams struct {
	BucketID uuid.UUID
	Key      string
}

// A tombstone rather than a row removal: the chunk list has to survive until
// refcounts have been decremented and GC has run.
func (q *Queries) SoftDeleteObject(ctx context.Context, arg SoftDeleteObjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteObject, arg.BucketID, arg.Key)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
