// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	BucketUsedBytes(ctx context.Context, bucketID uuid.UUID) (int64, error)
	// Demotes the current version of a key. Run inside CommitObject's transaction
	// immediately before inserting the new one, so the unique partial index on
	// (bucket_id, key) WHERE is_latest is never violated and no reader ever sees
	// zero or two current versions.
	ClearLatestVersion(ctx context.Context, arg ClearLatestVersionParams) error
	CreateBucket(ctx context.Context, arg CreateBucketParams) (Bucket, error)
	// Decrements every chunk referenced by an object version. Clamped at zero so a
	// double delete cannot drive the count negative and trip the CHECK constraint.
	DecrementChunkRefcounts(ctx context.Context, objectID uuid.UUID) error
	DeleteBucket(ctx context.Context, name string) (int64, error)
	DeleteChunk(ctx context.Context, id []byte) (int64, error)
	GetBucketByName(ctx context.Context, name string) (Bucket, error)
	GetChunk(ctx context.Context, id []byte) (Chunk, error)
	GetLatestObject(ctx context.Context, arg GetLatestObjectParams) (Object, error)
	GetNode(ctx context.Context, id string) (Node, error)
	// One query returns an object's whole chunk list with every live location,
	// so reading an object costs a single round trip to the coordinator rather
	// than one per chunk.
	GetObjectChunkPlacements(ctx context.Context, objectID uuid.UUID) ([]GetObjectChunkPlacementsRow, error)
	GetObjectVersion(ctx context.Context, arg GetObjectVersionParams) (Object, error)
	GetPlacements(ctx context.Context, chunkID []byte) ([]GetPlacementsRow, error)
	IncrementChunkRefcount(ctx context.Context, id []byte) error
	InsertObject(ctx context.Context, arg InsertObjectParams) (Object, error)
	InsertObjectChunk(ctx context.Context, arg InsertObjectChunkParams) error
	ListBuckets(ctx context.Context) ([]Bucket, error)
	// Tombstoned versions whose chunks are ready to be dereferenced.
	ListDeletableObjects(ctx context.Context, arg ListDeletableObjectsParams) ([]Object, error)
	ListLiveNodes(ctx context.Context) ([]Node, error)
	ListNodes(ctx context.Context) ([]Node, error)
	ListObjectVersions(ctx context.Context, arg ListObjectVersionsParams) ([]Object, error)
	// Keyset pagination on (key): stable under concurrent writes, unlike OFFSET,
	// and the continuation token is just the last key returned.
	ListObjects(ctx context.Context, arg ListObjectsParams) ([]Object, error)
	// GC candidates: no references left, and old enough that an upload in flight
	// cannot still be about to reference them.
	ListUnreferencedChunks(ctx context.Context, arg ListUnreferencedChunksParams) ([]Chunk, error)
	MarkPlacementBad(ctx context.Context, arg MarkPlacementBadParams) error
	PurgeObject(ctx context.Context, id uuid.UUID) error
	SetNodeState(ctx context.Context, arg SetNodeStateParams) error
	// A tombstone rather than a row removal: the chunk list has to survive until
	// refcounts have been decremented and GC has run.
	SoftDeleteObject(ctx context.Context, arg SoftDeleteObjectParams) (int64, error)
	UpdateNodeUsage(ctx context.Context, arg UpdateNodeUsageParams) error
	// Returns xmax = 0 when the row was inserted rather than updated, which is how
	// we tell a genuinely new chunk from a deduplication hit in a single round trip.
	UpsertChunk(ctx context.Context, arg UpsertChunkParams) (UpsertChunkRow, error)
	UpsertNode(ctx context.Context, arg UpsertNodeParams) (Node, error)
	UpsertPlacement(ctx context.Context, arg UpsertPlacementParams) error
}

var _ Querier = (*Queries)(nil)
